Use separate job for extracting version

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -21,7 +21,41 @@ env:
   REGISTRY_IMAGE: openproject/community
 
 jobs:
+  extract_version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Extract version
+        id: extract_version
+        run: |
+          if [[ ${{ github.event_name }} == 'push' ]]; then
+            TAG_REF=${GITHUB_REF#refs/tags/}
+            CHECKOUT_REF=$GITHUB_REF
+          elif [[ ${{ github.event_name }} == 'schedule' ]]; then
+            TAG_REF=dev
+            CHECKOUT_REF=refs/heads/dev
+          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
+            TAG_REF=${{ inputs.tag }}
+            CHECKOUT_REF=${{ inputs.tag }}
+          else
+            echo "Unsupported event"
+            exit 1
+          fi
+
+          if [ -z "$TAG_REF" ] || [ -z "$CHECKOUT_REF" ]; then
+            echo "No TAG_REF or CHECKOUT_REF set. Aborting"
+            exit 1
+          fi
+
+          VERSION=${TAG_REF#v}
+          echo "Version: $VERSION"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+          echo "checkout_ref=$CHECKOUT_REF" >> "$GITHUB_OUTPUT"
+    outputs:
+      version: ${{ steps.extract_version.outputs.version }}
+      checkout_ref: ${{ steps.extract_version.outputs.checkout_ref }}
   build:
+    needs:
+      - extract_version
     if: github.repository == 'opf/openproject'
     runs-on: [ self-hosted, aws, ubuntu22, x64, 2XL ]
     strategy:
@@ -48,7 +82,7 @@ jobs:
           elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
             TAG_REF=${{ inputs.tag }}
           fi
-          
+
           VERSION=${TAG_REF#v}
           echo "Version: $VERSION"
           echo "::set-output name=version::$VERSION"
@@ -78,7 +112,7 @@ jobs:
         uses: docker/metadata-action@v4
         with:
           tags: |
-            type=semver,pattern={{version}},value=${{ steps.extract_version.outputs.version }}
+            type=semver,pattern={{version}},value=${{ needs.extract_version.outputs.version }}
           images: |
             ${{ env.REGISTRY_IMAGE }}
       - name: Build image
@@ -139,6 +173,7 @@ jobs:
       matrix:
         target: [slim, all-in-one]
     needs:
+      - extract_version
       - build
     steps:
       - name: Download digests
@@ -167,9 +202,9 @@ jobs:
             latest=false
             suffix=${{ steps.set_suffix.outputs.suffix }}
           tags: |
-            type=semver,pattern={{version}},value=${{ steps.extract_version.outputs.version }}
-            type=semver,pattern={{major}}.{{minor}},value=${{ steps.extract_version.outputs.version }}
-            type=semver,pattern={{major}},value=${{ steps.extract_version.outputs.version }}
+            type=semver,pattern={{version}},value=${{ needs.extract_version.outputs.version }}
+            type=semver,pattern={{major}}.{{minor}},value=${{ needs.extract_version.outputs.version }}
+            type=semver,pattern={{major}},value=${{ needs.extract_version.outputs.version }}
             type=raw,value=dev,priority=200,enable={{is_default_branch}}
       - name: Login to Docker Hub
         uses: docker/login-action@v2
